SOURCES = \
					src/builtin.c \
					src/debug.c \
					src/execute.c \
					src/hashtable.c \
					src/line.c \
					src/list.c \
					src/redirect.c \
					src/shell.c \
					src/tokenize.c \
					src/util.c \
					src/variable.c \
					src/parse.c \

OBJECTS = ${SOURCES:.c=.o}
HEADERS = ${SOURCES:.c=.h}
